version: '3'

services:

  postgres:
    image: postgres:11.3
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/sql:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=oms-consumer-api
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
